<script type="text/x-magento-init">
{
    "*":{
        "elogicSlider":{
            "template":".brands",
            "slickOptions":{
                "infinite": true,
                "slidesToShow": 5,
                "slidesToScroll": 1,
                "arrows": true,
                "dots": true,
                "autoplay": true,
                "autoplaySpeed": 5000,
                "variableWidth": false,
                "responsive": [
                    {
                        "breakpoint": 1100,
                        "settings":{
                            "slidesToShow": 4,
                            "slidesToScroll": 1
                        }
                    },
                    {
                        "breakpoint": 725,
                        "settings":{
                            "slidesToShow": 3,
                            "slidesToScroll": 1
                        }
                    },
                    {
                        "breakpoint": 550,
                        "settings":{
                            "slidesToShow": 2,
                            "slidesToScroll": 1
                        }
                    },
                    {
                        "breakpoint": 400,
                        "settings":{
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
}
</script>
