<script type="text/x-magento-init">
{
    "*":{
        "elogicSlider":{
            "template":"#home-our-products .product-items",
            "slickOptions":{
                    "infinite": true,
                    "arrows": true,
                    "slidesToShow": 4,
                    "slidesToScroll": 4,
                    "variableWidth": false,
                    "responsive": [
                        {
                            "breakpoint": 1350,
                            "settings":{
                                "slidesToShow": 3,
                                "slidesToScroll": 3
                            }
                        },
                        {
                            "breakpoint": 990,
                            "settings": {
                                "slidesToShow": 2,
                                "slidesToScroll": 2
                            }
                        },
                        {
                            "breakpoint": 660,
                            "settings": {
                                "slidesToShow": 1,
                                "slidesToScroll": 1
                            }
                        }
                    ]
            }
        }
    }
}
</script>
