<script type="text/x-magento-init">
{
    "*":{
        "elogicSlider":{
        "template":"#top-home-slider",
        "slickOptions":{
                "infinite": false,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000,
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "dots": true
            }
        }
    }
}
</script>
