<?php
/**
 *  @var \Elogic\Newsletter\Block\IsSubscribedNewsletter $block;
 */

$_subscribeCustomerStatus = $block->checkCustomerIsSubscribe();
?>

<script type="text/x-magento-init">
{
    ".subscribe-modal-container":{
        "elogicModalSubscription":{
        "isCustomerSubscribed": <?= /* @noEscape */ $_subscribeCustomerStatus ? 'true' : 'false' ?>,
        "checkBox": "#modal-subscribe-dont_show_again",
        "modalOptions":{
                "autoOpen": true,
                "clickableOverlay": true
            }
        }
    }
}
</script>
