<div class="banners">
        <div class="blockdesc">
            <img src="{{media url="wysiwyg/banners/banner-home3-1.jpg"}}" alt="clocks">
            <div class="descr">
                <h2>Clocks</h2>
                <p>The 1958 moulded plywood armchair by Norman Cherner</p>
                <div class="underline"><a href="#">View now</a></div>
            </div>
        </div>
        <div class="blockdesc">
            <img src="{{media url="wysiwyg/banners/banner-home3-2.jpg"}}" alt="lights">
            <div class="descr">
                <h2><span class="new">New</span> Lights</h2>
                <p>The 1958 moulded plywood armchair by Norman Cherner</p>
                <div class="underline"><a href="#">View now</a></div>
            </div>
        </div>
</div>
