<div class="top-of-block">
    <h2>Our Products</h2>
    <p>Most trendy furniture</p>
    <div class="line-with-buttons">
        <div class="line-gor">&nbsp;</div>
        <div class="owl-buttons">
            <div class="owl-prev">
                <p>Prev</p>
            </div>
            <div class="line-ver">&nbsp;</div>
            <div class="owl-next">
                <p>Next</p>
            </div>
        </div>
    </div>
</div>
<p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`9`^]^]"}}</p>
