//
//  first display
//  _____________________________________________

<div id="top-home-slider" class="first-display">
    <div class="home1">
        <img src="{{media url="wysiwyg/banners/home3-1.jpg"}}" alt="">
        <div class="descr">
            <h2>Clearance</h2>
            <span class="new">Giver a timeless classic a home</span>
            <p>It is a long established fact that a reader will</p>
        </div>
        {{widget class="underline" type="Magento\Catalog\Block\Product\Widget\Link" anchor_text="View now" template="product/widget/link/link_block.phtml" id_path="product/2054/41"}}</div>
    <div class="home2">
        <img src="{{media url="wysiwyg/banners/home3-2.jpg"}}" alt="">
        <div class="descr">
            <h2><span class="new">Cherner</span> Armchair</h2>
            <p>The 1958 moulded plywood armchair by Norman Cherner</p>
        </div>
        {{widget class="underline" type="Magento\Catalog\Block\Product\Widget\Link" anchor_text="View now" template="product/widget/link/link_block.phtml" id_path="product/2055/41"}}</div>
</div>

//
//  banners
//  _____________________________________________

<div class="banners">
    <div class="blockdesc">
        <img src="{{media url="wysiwyg/banners/banner-home3-1.jpg"}}" alt="clocks">
        <div class="descr">
            <h2>Clocks</h2>
            <p>The 1958 moulded plywood armchair by Norman Cherner</p>
            <a class="underline" href="#">View now</a>
        </div>
    </div>
    <div class="blockdesc">
        <img src="{{media url="wysiwyg/banners/banner-home3-2.jpg"}}" alt="lights">
        <div class="descr">
            <h2><span class="new">New</span> Lights</h2>
            <p>The 1958 moulded plywood armchair by Norman Cherner</p>
            <a class="underline" href="#">View now</a>
        </div>
    </div>
</div>

//
//  productList
//  _____________________________________________

<div class="top-of-block">
    <h2>Our Products</h2>
    <p>Most trendy furniture</p>
    <div class="lines">
        <div class="line-gor">&nbsp;</div>
        <div class="line-ver">&nbsp;</div>
    </div>
</div>
<p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`9`^]^]"}}</p>

//
//  novemberSale
//  _____________________________________________

<div class="nov-sale">
    <img src="{{media url="wysiwyg/banners/banner-home3-3.jpg"}}" alt="">
    <div class="sale-text-with-link">
        <div class="sale-text">
            <h2>November Sale</h2>
            <p>Free Shipping over $125 For International Orders</p>
        </div>
        <a class="underline" href="#">Shop Now</a>
    </div>
</div>

//
//  Triple Slider
//  _____________________________________________

<div class="triple-slider">
    <div class="triple-slider-item">
        <h2>Bestsellers</h2>
        <div class="line-ver"></div>
        {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`41`^]^]"}}
    </div>
    <div class="triple-slider-item">
        <h2>Featured</h2>
        <div class="line-ver"></div>
        {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`41`^]^]"}}
    </div>
    <div class="triple-slider-item">
        <h2>Most Viewed</h2>
        <div class="line-ver"></div>
        {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`41`^]^]"}}
    </div>
</div>

//
//  News & Blog
//  _____________________________________________

<div class="top-of-block">
    <h2>News &amp; Blog</h2>
    <p>Most trendy furniture</p>
    <div class="lines">
        <div class="line-gor">&nbsp;</div>
        <div class="line-ver">&nbsp;</div>
    </div>
</div>
<div class="news-blog">
    <div class="news-blog-item"><img src="{{media url="wysiwyg/newsAndBlog/09_4.jpg"}}" alt="">
        <h3>Aptent taciti soci litora cianpen</h3>
        <div class="date-time">16-May-2017</div>
        <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
    </div>
    <div class="news-blog-item"><img src="{{media url="wysiwyg/newsAndBlog/04_4.jpg"}}" alt="">
        <h3>Mauris gravida nulla turpis</h3>
        <div class="date-time">16-May-2017</div>
        <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
    </div>
    <div class="news-blog-item"><img src="{{media url="wysiwyg/newsAndBlog/03_4.jpg"}}" alt="">
        <h3>Fusce gravida maximus elit</h3>
        <div class="date-time">16-May-2017</div>
        <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
    </div>
    <div class="news-blog-item"><img src="{{media url="wysiwyg/newsAndBlog/05_2.jpg"}}" alt="">
        <h3>Integer urna nuncve hicula</h3>
        <div class="date-time">16-May-2017</div>
        <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
    </div>
    <div class="news-blog-item"><img src="{{media url="wysiwyg/newsAndBlog/04_4.jpg"}}" alt="">
        <h3>Mauris gravida nulla turpis</h3>
        <div class="date-time">16-May-2017</div>
        <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
    </div>
</div>

//
//  Brands
//  _____________________________________________

<div class="title-of-block">
    <hr>
    <strong>Shop By Brands</strong>
    <hr>
</div>
<div class="line-ver"></div>

<div class="brands">
    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand1_bc12606a864d8675c6f925455b3c32eb.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/hammary.html" title="Hammary">Hammary</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand2_af4945628435df11a3de0686bd9c4157.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/herman-miller.html" title="Herman Miller"> Herman Miller</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand3_5bba384c08d51704fbc44238fc1f075b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/stressless.html" title="Stressless">Stressless</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand5_7015ca7a49836d2461f226edc65db20b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/greenington.html" title="Greenington">Greenington</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand1_bc12606a864d8675c6f925455b3c32eb.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/knoll.html" title="Knoll">Knoll</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand6_54f5ad48f6c2071a4f8793628d354b5b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/innovation.html" title="Innovation">Innovation</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand554_4de3b39e3441597716a4aea7924babd3.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/american-drew.html" title="American Drew">American Drew</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand5_7015ca7a49836d2461f226edc65db20b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/younger.html" title="Younger">Younger</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand2_af4945628435df11a3de0686bd9c4157.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/lexington.html" title="Lexington">Lexington</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand3_5bba384c08d51704fbc44238fc1f075b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/tommy-bahama-home.html" title="Tommy Bahama Home">Tommy Bahama Home</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand1_bc12606a864d8675c6f925455b3c32eb.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/copeland.html" title="Copeland">Copeland</a>
        </div>
    </div>

    <div class="brands-item">
        <img src="{{media url=&quot;wysiwyg/brands/brand6_54f5ad48f6c2071a4f8793628d354b5b.jpg&quot;}}" alt="" />
        <div class="brands-name">
            <a href="https://blueskytechmage.com/drexel/en2/brand/stanley.html" title="Stanley">Stanley</a>
        </div>
    </div>
</div>

//
//  Footer
//  _____________________________________________

<div class="footer-content">
    <div class="footer-top">
        <div class="footer-container">

            <div class="footer-links-item">
                <h2 class="title"><a href="#">About</a></h2>
                <ul>
                    <li><a href="#">News &amp; Stories</a></li>
                    <li><a href="#">History</a></li>
                    <li><a href="#">Our Studio</a></li>
                    <li><a href="#">Showrooms</a></li>
                    <li><a href="#">Stockists</a></li>
                </ul>
            </div>

            <div class="footer-links-item">
                <h2 class="title"><a href="#">Customer services</a></h2>
                <ul>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Trade Services</a></li>
                    <li><a href="#">Login/Register</a></li>
                    <li><a href="#">Delivery &amp; Returns</a></li>
                    <li><a href="#">FAQs</a></li>
                </ul>
            </div>

            <div class="footer-links-item">
                <h2 class="title"><a href="#">Furniture</a></h2>
                <ul>
                    <li><a href="#">Tables</a></li>
                    <li><a href="#">Chairs</a></li>
                </ul>
            </div>

            <div class="footer-links-item">
                <h2 class="title"><a href="#">Accessories</a></h2>
                <ul>
                    <li><a href="#">Candles &amp; Fragrance</a></li>
                    <li><a href="#">Stationery</a></li>
                    <li><a href="#">Kitchen &amp; Dining</a></li>
                    <li><a href="#">Textiles</a></li>
                    <li><a href="#">Gifl Sets</a></li>
                </ul>
            </div>
        </div>
    </div>

        <div class="footer-bottom">
            <div class="footer-container">
                <div class="footer-link-row">
                    <ul class="link-row">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">FAQs</a></li>
                        <li><a href="#">Order Tracking</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>

                <div class="footer-social">
                    <p>Connect with us:</p>
                    <ul class="link-social">
                        <li><a class="behance" href="#"></a></li>
                        <li><a class="facebook" href="#"></a></li>
                        <li><a class="google" href="#"></a></li>
                        <li><a class="skype " href="#"></a></li>
                        <li><a class="twitter" href="#"></a></li>
                    </ul>
                </div>
        </div>
    </div>
</div>

//
//  Modal Subscribe
//  _____________________________________________

<div class="modal-subscribe">
    <div class="modal-subscribe-info">
        <h3>Get Our Email Letter</h3>
        <div class="modal-subscribe-text">
            <p>Subscribe to the Boutique mailing list to receive updates on new arrivals!</p>
        </div>
        <div class="modal-check-show">
            <input id="modal-subscribe-dont_show_again" type="checkbox"> <label class="modal-dont-show-label" for="modal-subscribe-dont_show_again">Do not show this popup again</label>
        </div>
    </div>
</div>

//
//  Header
//  _____________________________________________

<div class="header-all-links">
    <ul class="header-navigation">
        <li class="nav-item">
            <a class="header-nav-link" href="https://blueskytechmage.com/drexel/en2/"><span>Home</span></a>
            <div class="submenu1" style="left: 0px; right: auto; border-radius: 0px 6px 6px;">
                <ul class="submenu">
                    <li class="submenu-item"><a href="http://blueskytechmage.com/magento/drexel/"><span>Home page 1</span></a></li>
                    <li class="submenu-item"><a href="http://blueskytechmage.com/magento/drexel/en1/"><span>Home page 2</span></a></li>
                    <li class="submenu-item"><a href="http://blueskytechmage.com/magento/drexel/en2/"><span>Home page 3</span></a></li>
                    <li class="submenu-item"><a href="http://blueskytechmage.com/magento/drexel/en3/"><span>Home page 4</span></a></li>
                    <li class="submenu-item"><a href="http://blueskytechmage.com/magento/drexel/en4/"><span>Home page 5</span></a></li>
                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="header-nav-link mega-link" href="https://blueskytechmage.com/drexel/en2/"><span>Arm Chair</span></a>
        </li>

        <li class="nav-item">
            <a class="header-nav-link" href="https://blueskytechmage.com/drexel/en2/"><span>Recliner</span></a>
            <div class="submenu1" style="left: 0px; right: auto; border-radius: 0px 6px 6px;">
                <ul class="submenu">

                    <li class="submenu-item">
                        <a href="https://blueskytechmage.com/drexel/en2/handmade/dental-care.html">
                            <span>Dental care</span>
                        </a>
                    </li>
                    <li class="submenu-item">
                        <a href="https://blueskytechmage.com/drexel/en2/handmade/desktop.html">
                            <span>Desktop</span>
                        </a>
                        <ul class="submenu2" style="left: 100%; right: auto; border-radius: 0px 6px 6px;">
                            <li class="submenu2-item">
                                <a href="https://blueskytechmage.com/drexel/en2/handmade/desktop/camcorders.html">
                                    <span>Camcorders</span>
                                </a>
                            </li>
                            <li class="submenu2-item">
                                <a href="https://blueskytechmage.com/drexel/en2/handmade/desktop/cameras.html">
                                    <span>Cameras</span>
                                </a>
                            </li>
                            <li class="submenu2-item">
                                <a href="https://blueskytechmage.com/drexel/en2/handmade/desktop/car-electronics.html">
                                    <span>Car Electronics</span>
                                </a>
                            </li>
                            <li class="submenu2-item">
                                <a href="https://blueskytechmage.com/drexel/en2/handmade/desktop/ceiling-fans.html">
                                    <span>Ceiling fans</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="submenu-item">
                        <a href="https://blueskytechmage.com/drexel/en2/handmade/davenport.html">
                            <span>Davenport</span>
                        </a>
                    </li>
                    <li class="submenu-item">
                        <a href="https://blueskytechmage.com/drexel/en2/handmade/digital.html">
                            <span>Digital</span>
                        </a>
                    </li>

                </ul>
            </div>
        </li>

        <li class="nav-item">
            <a class="header-nav-link" href="#"><span>Features</span></a>
            <div class="submenu1" style="left: 0px; right: auto; border-radius: 0px 6px 6px;">

                <ul class="submenu">
                    <li class="submenu-item"><a href="https://blueskytechmage.com/drexel/en2/blog/"><span>Blog</span></a></li>
                    <li class="submenu-item"><a href="https://blueskytechmage.com/drexel/en2/fashion.html/"><span>Layered Ajax</span></a></li>
                    <li class="submenu-item">
                        <a href="#"><span>Product Types</span></a>
                        <ul class="submenu2" style="left: -9999px; right: auto;">
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/hollister-backyard-sweatshirt-10.html/"><span>Simple Product</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/frankie-sweatshirt.html/"><span>Custom option product</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/hollister-backyard-sweatshirt-1000.html/"><span>Grouped Product</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/fashion/clothing.html/"><span>Configurable Product</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/mars-heattechtm-pullover100.html/"><span>Bundle Product</span></a></li>
                        </ul>
                    </li>
                    <li class="submenu-item">
                        <a href="https://blueskytechmage.com/drexel/en2/"><span>Product Features</span></a>
                        <ul class="submenu2" style="left: -9999px; right: auto;">
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/hollister-backyard-sweatshirt-7.html/"><span>Product with Video</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/hollister-backyard-sweatshirt-13.html/"><span>Product with Related</span></a></li>
                            <li class="submenu2-item"><a href="https://blueskytechmage.com/drexel/en2/hollister-backyard-sweatshirt-1.html/"><span>Product with Upsell</span></a></li>
                        </ul>
                    </li>
                </ul>

            </div>
        </li>

        <li class="nav-item">
            <a class="header-nav-link" href="https://blueskytechmage.com/drexel/en2/rokanthemes-brand.html"><span>Brands</span></a>
        </li>
    </ul>

    <div class="header-link-right">
        <div class="header-right-item">
            <a class="header-login" href="#">Log In</a>
        </div>
        <div class="header-right-item">
            <a class="header-wishlist" href="#"></a>
        </div>
        <div class="header-right-item">
            <a class="header-cart" href="#">Cart</a>
        </div>
        <div class="header-right-item">
            <a class="header-serch" href="#"></a>
        </div>
        <div class="header-right-item">
            <a class="header-languages" href="#"></a>
        </div>
    </div>
</div>



