<script type="text/x-magento-init">
{
    "*":{
        "elogicSlider":{
            "template":"#category-sidebar-slider",
            "slickOptions":{
                "infinite": true,
                "arrows": false,
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "autoplay": true,
                "autoplaySpeed": 5000,
                "dots": true
            }
        }
    }
}
</script>
